/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Catalog: () => import('#controllers/catalog_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Procurement: () => import('#controllers/procurement_controller'),
  Session: () => import('#controllers/session_controller'),
}
