/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CatalogItemSchema extends BaseModel {
  static $columns = ['category', 'description', 'id', 'inStock', 'leadTimeDays', 'manufacturer', 'model', 'name', 'priceUsd', 'specs', 'supplier'] as const
  $columns = CatalogItemSchema.$columns
  @column()
  declare category: string
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare inStock: boolean
  @column()
  declare leadTimeDays: number
  @column()
  declare manufacturer: string
  @column()
  declare model: string
  @column()
  declare name: string
  @column()
  declare priceUsd: number
  @column()
  declare specs: any
  @column()
  declare supplier: string
}

export class PurchaseOrderLineSchema extends BaseModel {
  static $columns = ['id', 'itemId', 'leadTimeDays', 'lineTotal', 'purchaseOrderId', 'quantity', 'unitPrice'] as const
  $columns = PurchaseOrderLineSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: string
  @column()
  declare leadTimeDays: number
  @column()
  declare lineTotal: number
  @column()
  declare purchaseOrderId: number
  @column()
  declare quantity: number
  @column()
  declare unitPrice: number
}

export class PurchaseOrderStatusEventSchema extends BaseModel {
  static $columns = ['changedAt', 'fromStatus', 'id', 'purchaseOrderId', 'reason', 'toStatus'] as const
  $columns = PurchaseOrderStatusEventSchema.$columns
  @column.dateTime()
  declare changedAt: DateTime
  @column()
  declare fromStatus: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare purchaseOrderId: number
  @column()
  declare reason: string | null
  @column()
  declare toStatus: string
}

export class PurchaseOrderSchema extends BaseModel {
  static $columns = ['costCenter', 'createdAt', 'id', 'neededByDate', 'paymentTerms', 'poNumber', 'requestor', 'status', 'supplier', 'updatedAt'] as const
  $columns = PurchaseOrderSchema.$columns
  @column()
  declare costCenter: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.date()
  declare neededByDate: DateTime
  @column()
  declare paymentTerms: string
  @column()
  declare poNumber: string
  @column()
  declare requestor: string
  @column()
  declare status: string
  @column()
  declare supplier: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
